class ActionInfo:
    def __init__(self, dx, dy, panel):
        self.dx = dx
        self.dy = dy
        self.panel = panel


# MOVE and PANEL : upper, lower
ACTION_ID_UPPER = 16
ACTION_ID_LOWER = 0

# Move Const Values
MOVE_UP = 0
MOVE_RIGHT_UP = 1
MOVE_RIGHT = 2
MOVE_RIGHT_DOWN = 3
MOVE_DOWN = 4
MOVE_LEFT_DOWN = 5
MOVE_LEFT = 6
MOVE_LEFT_UP = 7

# Panel Const Values
PANEL_UP = 8
PANEL_RIGHT_UP = 9
PANEL_RIGHT = 10
PANEL_RIGHT_DOWN = 11
PANEL_DOWN = 12
PANEL_LEFT_DOWN = 13
PANEL_LEFT = 14
PANEL_LEFT_UP = 15

# Stay
STAY = 16

# Actions
ACTION = [None] * 17

ACTION[MOVE_UP] = ActionInfo(0, -1, 0)
ACTION[MOVE_RIGHT_UP] = ActionInfo(1, -1, 0)
ACTION[MOVE_RIGHT] = ActionInfo(1, 0, 0)
ACTION[MOVE_RIGHT_DOWN] = ActionInfo(1, 1, 0)
ACTION[MOVE_DOWN] = ActionInfo(0, 1, 0)
ACTION[MOVE_LEFT_DOWN] = ActionInfo(-1, 1, 0)
ACTION[MOVE_LEFT] = ActionInfo(-1, 0, 0)
ACTION[MOVE_LEFT_UP] = ActionInfo(-1, -1, 0)

ACTION[PANEL_UP] = ActionInfo(0, -1, 1)
ACTION[PANEL_RIGHT_UP] = ActionInfo(1, -1, 1)
ACTION[PANEL_RIGHT] = ActionInfo(1, 0, 1)
ACTION[PANEL_RIGHT_DOWN] = ActionInfo(1, 1, 1)
ACTION[PANEL_DOWN] = ActionInfo(0, 1, 1)
ACTION[PANEL_LEFT_DOWN] = ActionInfo(-1, 1, 1)
ACTION[PANEL_LEFT] = ActionInfo(-1, 0, 1)
ACTION[PANEL_LEFT_UP] = ActionInfo(-1, -1, 1)

ACTION[STAY] = ActionInfo(0, 0, 0)

# dx,dy to Action
DXDY_ACTION_TABLE = {}

DXDY_ACTION_TABLE[(0, -1, 0)] = MOVE_UP
DXDY_ACTION_TABLE[(1, -1, 0)] = MOVE_RIGHT_UP
DXDY_ACTION_TABLE[(1, 0, 0)] = MOVE_RIGHT
DXDY_ACTION_TABLE[(1, 1, 0)] = MOVE_RIGHT_DOWN
DXDY_ACTION_TABLE[(0, 1, 0)] = MOVE_DOWN
DXDY_ACTION_TABLE[(-1, 1, 0)] = MOVE_LEFT_DOWN
DXDY_ACTION_TABLE[(-1, 0, 0)] = MOVE_LEFT
DXDY_ACTION_TABLE[(-1, -1, 0)] = MOVE_LEFT_UP

DXDY_ACTION_TABLE[(0, -1, 1)] = PANEL_UP
DXDY_ACTION_TABLE[(1, -1, 1)] = PANEL_RIGHT_UP
DXDY_ACTION_TABLE[(1, 0, 1)] = PANEL_RIGHT
DXDY_ACTION_TABLE[(1, 1, 1)] = PANEL_RIGHT_DOWN
DXDY_ACTION_TABLE[(0, 1, 1)] = PANEL_DOWN
DXDY_ACTION_TABLE[(-1, 1, 1)] = PANEL_LEFT_DOWN
DXDY_ACTION_TABLE[(-1, 0, 1)] = PANEL_LEFT
DXDY_ACTION_TABLE[(-1, -1, 1)] = PANEL_LEFT_UP

DXDY_ACTION_TABLE[(0, 0, 0)] = STAY

# Generate Board Options
LINE_SYMMETRY_HALF = 0
LINE_SYMMETRY_QUOTER = 1
POINT_SYMMETRY_HALF = 2
